name: dynDWI
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - scikit-image
  - statsmodels
  - nibabel
  - dipy
  - pillow
  - tqdm
  - pywavelets
  - pip
  - pip:
      - cmasher
      - colorspacious